apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vk5jpjcoc-go-gitops
  description: This is GitOps manifest for vk5jpjcoc-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=vk5jpjcoc-go
    backstage.io/kubernetes-id: vk5jpjcoc-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: vk5jpjcoc-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:vk5jpjcoc-go
