apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vk5jpjcoc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vk5jpjcoc-go 
  name: vk5jpjcoc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vk5jpjcoc-go 
